### ISSUE TITLE
Issue with DTS agent startup due to memory utilization checks

### ISSUE THREAD

**Issue by Raniksingh** [GoogleCloudPlatform/data-migration-tool#17]
There are internal checks performed to calculate if there is 30% free memory threshold in the agent VM before starting DTS agent. 
DMT calculates this threshold memory using (free mem/total * 100) to make sure it passes the checks before agent is initialised .
However we have noticed in certain VMs most of the memory gets allocated in the buffer/cache and free memory goes <30% and the pre-checks doesn't consider buffer/cache memory available.
And agent initialisation starvs with below logs : 
start.log  (Agent is waiting for Memory free to reach 30% which is causing starvation)
```
Thu Nov  9 14:54:52 UTC 2023
Transfer ID: 65655261-0000-29f0-a235-f4f5e806a1f4
Thu Nov  9 14:54:52 UTC 2023
Memory Free: 21%
Sleeping 60 seconds
Thu Nov  9 14:55:52 UTC 2023
Memory Free: 21%
Sleeping 60 seconds
Thu Nov  9 14:56:52 UTC 2023
Memory Free: 21%
Sleeping 60 seconds
```

<img width="533" alt="image" src="https://github.com/GoogleCloudPlatform/data-migration-tool/assets/100393188/5266ad72-0e7a-4767-adaf-fcc262bea365">

To make use of memory in buffer/cache we need to modify the internal checks.

**Comment by forksumit** [comment]
https://github.com/GoogleCloudPlatform/data-migration-tool/blob/main/src/datamigration/scripts/teradata/agent_controller/scripts/start_agent.sh#L39

```
mem_free=$(free | grep Mem | awk '{print $4/$2 * 100.0}' | cut -d . -f 1)
```

Currently `start_agent.sh` calculates free memory by **_free ($4) / total ($2) * 100_** which ignore buff/cache memory , changing it to **_available ($7) / total ($2) * 100_** (which considers buff/cache memory as well) should fix the issue
